### ISSUE TITLE
Use Whirl in your CI

### ISSUE THREAD

**Issue by bjgbeelen** [godatadriven/whirl#16]
Let's see if we can use Whirl in our CI to actually run a DAG and test that the DagRun turned successful

**Comment by ilyanoskov** [comment]
@bjgbeelen this feature would be great! really looking forward to this

**Comment by krisgeus** [comment]
@ilyanoskov @bjgbeelen https://github.com/godatadriven/whirl/pull/61 add airflow 2.x style unpause and dagrun status checks. 
The command `../../whirl -e postgres-s3-spark ci` from within the `examples/spark-s3-to-postgres/` directory:
- builds the images
- starts the environment
- waits until the airlfow UI is available
- unpauses the dag (dag_id is retrieved from the dag.py file)
- checks the running state of the dag in a loop
- checks the final dagrun state (`success` or `failure`) and exits with status `0` (success) or `1` (failure)
- stops the environment

**Comment by krisgeus** [comment]
It is tested locally on my mac and works at least for this dag and environment. I'm planning to check all other examples too.
Next step is https://github.com/godatadriven/whirl/issues/34 to add github actions to the repo to prove this works ;-)

**Comment by krisgeus** [comment]
Closed with #64
