### ISSUE TITLE
No module named 'werkzeug.wrappers.json' error

### ISSUE THREAD

**Issue by vanducng** [godatadriven/whirl#50]
Hi @bjgbeelen 
Can you advise below error. This is a first time examining with whirl for the first example "**SSH to Localhost**". 
There are couple of errors "No module named 'werkzeug.wrappers.json';" at step 29/29 and then exit with code 1.

```bash
airflow_1  | ModuleNotFoundError: No module named 'werkzeug.wrappers.json'; 'werkzeug.wrappers' is not a package
local-ssh_airflow_1 exited with code 1
```

**Comment by vanducng** [comment]
I did modify the Dockerfile as below and rerun `whirl start -e local-ssh` and it runs as normal. However i don't think it is a best way.
![image](https://user-images.githubusercontent.com/2980905/60752320-1da69500-9fee-11e9-9292-dabef1fb3a73.png)

**Comment by Fokko** [comment]
Interesting one @vanducng 

This has been fixed in Airflow upstream: https://github.com/apache/airflow/pull/5535
