### ISSUE TITLE
Add >2.1.x Support

### ISSUE THREAD

**Issue by mkramer5454** [godatadriven/whirl#67]
Airflow removed the AIRFLOW_GID parameter causing the whirl build to break for airflow version 2.2+ - relevant airflow commit [here](https://github.com/apache/airflow/commit/958860fcd7c9ecdf60b7ebeef4397b348835c8db) and failing whirl line [here](https://github.com/godatadriven/whirl/blob/master/docker/airflow-python/Dockerfile#L16)

Exact error message when setting airflow_version=2.2.2:
```
 => [ 3/10] RUN mkdir -p "/etc/airflow/whirl.setup.d/dag.d"                                                                                                                                                                                                      0.3s
 => ERROR [ 4/10] RUN chown -R airflow:airflow "/etc/airflow/whirl.setup.d"                                                                                                                                                                                      0.3s
------
 > [ 4/10] RUN chown -R airflow:airflow "/etc/airflow/whirl.setup.d":
#7 0.246 chown: invalid group: 'airflow:airflow'
------
executor failed running [/bin/bash -o pipefail -c chown -R airflow:airflow "${WHIRL_SETUP_FOLDER}"]: exit code: 1
```

This is fixed by updating the whirl python docker file as so
```
RUN chown -R airflow:0 "${WHIRL_SETUP_FOLDER}"
```

Happy to help remediate!

**Comment by krisgeus** [comment]
Thx @mkramer5454 for mentioning this issue and suggesting this fix. We are planning to have a 2 day sprint to get a few Airflow 2 features into whirl (think example with HA scheduler, dags with @task decorators etc.) 
we will make sure we incorporate this fix too

**Comment by krisgeus** [comment]
Just remembered I already had a branch with this fix in it ;-) Feel free to review it @mkramer5454
