### ISSUE TITLE
Divolte issue

### ISSUE THREAD

**Issue by prk2331** [godatadriven/whirl#86]
hi @krisgeus 
sorry for that I am writing you here actually that Divolte repository has been archived by the owner, and I am stuck in one problem of **Divolte session Id** 

**1. every page refresh I am getting new session id, why session id wont be persist till their session timeout configured ?
2. How can we make a function so that we can close this session id manually without waiting for inactivity ?**

I am facing these issues
can you please guide me how can we solve this
This would be really helpful for me

Thanks

**Comment by krisgeus** [comment]
Hi. I have to close this issue since it is not for this project. From the top of my head I know divolte is using a session cookie to store the session Id. Things on the client side that prevent this coockie to be set or persisted might cause this issue. That's all the help I can give.
